{
    "Search - PlayCanvas Developer Resources": "搜索 - PlayCanvas 开发者资源",
    "Oh No!": "糟糕!",
    "PlayCanvas Developer Resources": "PlayCanvas 开发者资源",
    "Introduction": "简介",
    "Shader Editor": "",
    "Info Pane": "",
    "Nodes Pane": "",
    "Graph Editor": "",
    "Preview Pane": "",
    "Window Layout": "",
    "Assets Pane": "",
    "Texture Inspector": "",
    "Graph Inspector": "",
    "Inspector Pane": "",
    "Material Inspector": "",
    "Node Inspector": "",
    "Textures": "纹理",
    "Workflow": "工作流",
    "Overview": "总览",
    "File Handling": "",
    "Materials": "材质",
    "Nodes": "",
    "Parameter Nodes": "",
    "Sub Graphs": "",
    "Graphs": "",
    "Material Graphs": "",
    "Render a 3D model": "渲染 3D 模型",
    "Play a sound": "播放声音",
    "Create a cubemap": "创建Cubemap",
    "Delete an Entity": "删除实体",
    "Duplicate an Entity": "复制实体",
    "Move / Rotate / Scale an Entity": "平移 / 旋转 / 缩放 实体",
    "Create a new shader": "创建 shader",
    "Play an animation": "播放动画",
    "Create a skybox": "创建天空盒",
    "Create a shape like a box, sphere etc.": "创建形体（立方，球，其它）",
    "Add a script": "添加脚本",
    "Change the background color": "修改背景颜色",
    "Use real-time shadows": "使用实时阴影",
    "Use physics": "使用物理特性",
    "Delete an asset": "删除资源",
    "Upload assets": "上传资源",
    "Create an Entity": "创建实体",
    "Add a component": "添加组件",
    "Create a material": "创建材质",
    "Change the material of a model": "",
    "Create a light": "创建灯光",
    "Remove a component": "移除组件",
    "Glossary": "词汇表",
    "User Manual": "用户手册",
    "Made with PlayCanvas": "",
    "Your First App": "",
    "Creating an Account": "创建帐户",
    "Creating Organizations": "创建组织",
    "Organizations": "组织",
    "Managing Organizations": "管理组织",
    "Publishing": "发布",
    "Self-hosting": "自设服务器",
    "Facebook": "Facebook",
    "PlayCanvas Hosting": "PlayCanvas 服务",
    "Hosting using a CDN": "使用CDN进行托管",
    "Self-hosting for beginners": "面向初学者的自设服务器",
    "Communication with web pages": "网页传输",
    "Web": "网页",
    "Desktop": "桌面",
    "Mobile": "移动平台",
    "Apache Cordova": "",
    "Facebook Playable Ad": "",
    "Snapchat Playable Ad": "",
    "ironSource Playable Ad (MRAID)": "",
    "Playable Ads": "",
    "Engine-Only Users": "",
    "Code Editor": "编辑器",
    "Communication": "通信交互",
    "Migration Guide": "",
    "Loading Order": "加载顺序",
    "Scripting": "脚本",
    "Script Attributes": "脚本特性",
    "Using a Custom Engine": "",
    "Hot Reloading": "热点重加载",
    "Debugging": "调试",
    "Creating new scripts": "创建新脚本",
    "Anatomy of a script": "脚本构造",
    "Optimize Scene Format": "",
    "Device Pixel Ratio": "",
    "Optimization Guidelines": "优化参考",
    "Hardware Instancing": "",
    "Profiler": "分析器",
    "Mini Stats": "",
    "Performance": "性能",
    "Batching": "",
    "Optimizing Load Time": "",
    "Troubleshooting Performance": "故障排除性能",
    "Merging and resolving conflicts": "",
    "Branches": "",
    "Version Control": "版本控制",
    "View Changes": "",
    "Branch Workflows": "",
    "Checkpoints": "",
    "Animation Assets": "",
    "Anim Events": "",
    "Anim Layer Masks": "",
    "Animstategraph Assets": "",
    "Animation": "动画",
    "Anim Component": "",
    "Optimizing WebXR applications": "",
    "Types of XR experiences": "",
    "XR": "",
    "Using WebXR in PlayCanvas": "",
    "WebXR Input Sources in PlayCanvas": "",
    "User Interface Basics": "",
    "Input": "",
    "Text Elements": "",
    "Safe Area": "",
    "Localization": "",
    "Image Elements": "",
    "Screens": "",
    "User Interface": "",
    "Layout Groups": "",
    "Elements": "",
    "Group Elements": "",
    "Scenes": "场景",
    "Layout Group": "",
    "Layout Child": "",
    "Particle System": "粒子系统",
    "Sprite": "",
    "Model": "模型",
    "Scrollview": "",
    "Button": "",
    "Camera": "摄影机",
    "Scrollbar": "",
    "Script": "脚本",
    "Anim": "",
    "Render": "",
    "Light": "灯光",
    "Components": "组件",
    "Sound": "声音",
    "Screen": "",
    "Audio Listener": "音频侦听器",
    "Element": "",
    "Collision": "碰撞",
    "Rigid Body": "刚体",
    "Entities": "实体",
    "Settings": "设置",
    "Dashboard Header": "指示板标题",
    "Dashboard": "指示板",
    "Account": "账户",
    "Projects": "项目",
    "Home": "首页",
    "Profile": "信息",
    "Assets": "资源",
    "Editor API": "",
    "Menu and Toolbar": "菜单与工具栏",
    "Viewport": "视口",
    "Keyboard Shortcuts": "快捷键",
    "Asset Library": "资源库",
    "Loading Screen": "载入界面",
    "Editor": "编辑器",
    "Inspector": "检查器",
    "Hierarchy": "层级树",
    "Assets - Get Asset File": "",
    "Projects - Archive project": "项目 - 项目归类",
    "Assets - Update asset": "",
    "Assets - Delete asset": "",
    "Assets - Create asset": "",
    "Assets - Get Asset": "",
    "Apps - Get primary app": "应用- 得到私有应用",
    "Branches - List branches": "",
    "REST API": "REST API",
    "Apps - Get app": "应用- 获取应用",
    "Jobs - Get job": "职位- 获得职位",
    "Assets - List assets": "",
    "Apps - Get project apps": "应用- 获取项目应用",
    "Apps - Download app": "应用- 应用下载",
    "Scenes - List scenes": "",
    "Override Diff View": "",
    "Nested Templates": "",
    "Templates": "",
    "Alternatives to ammo.js": "",
    "Ray Casting": "",
    "Physics": "物理",
    "Trigger Volumes": "",
    "Updating ammo.js": "",
    "Forces and Impulses": "力与冲量",
    "Calling the ammo.js API": "",
    "Physics Basics": "",
    "Cameras": "摄影机",
    "File Format": "文件格式",
    "Particles": "粒子",
    "Graphics": "图形",
    "Layers": "",
    "Physical Materials": "物理学材质",
    "Image Based Lighting": "",
    "Physically Based Rendering": "物理学渲染",
    "Shadows": "阴影",
    "Lightmapping": "",
    "Ambient Occlusion": "",
    "Lights": "灯光",
    "Lighting": "光照",
    "Runtime Lightmaps": "",
    "FXAA Effect": "FXAA 抗锯齿",
    "Bloom Effect": "Bloom 特效",
    "Vignette Effect": "暗角特效",
    "Hue-Saturation Effect": "色相-饱和度 特效",
    "Brightness-Contrast Effect": "明暗-对比度 特效",
    "Post Effects": "后处理特效",
    "Sepia Effect": "Sepia 特效",
    "CSS": "CSS",
    "Template": "",
    "Texture Atlas": "",
    "Preloading and Streaming": "预加载和流式加载",
    "Audio": "音频",
    "Font": "",
    "Cubemap": "",
    "Shader": "Shader",
    "Uploading and Importing": "上传和导入",
    "Finding Assets": "查找资源",
    "Wasm Module": "",
    "HTML": "HTML",
    "Texture Compression": "",
    "Texture": "",
    "Material": "",
    "Phong Material": "Phong 材质",
    "Physical Material": "物理学材质",
    "Exporting Assets": "导出资源",
    "Units": "单位",
    "Building Models": "制作模型",
    "Asset Import Pipeline": "资源导入流程",
    "Import Hierarchy": "",
    "9-slicing": "",
    "2D": "",
    "Sprite Editor": "",
    "Billing": "",
    "Basic Audio": "音频入门",
    "Facebook API": "Facebook API接口",
    "Manipulating Entities": "实体管理",
    "Making a Simple Game - Part 2": "制作轻量游戏 - Part 2",
    "Making a Simple Game - Part 5": "制作轻量游戏 - Part 5",
    "Animated Textures": "动画纹理",
    "Basic Cameras": "摄影机入门",
    "More Cameras": "多摄影机位",
    "Controlling Lights": "灯光管理",
    "Anim State Graph Blending": "",
    "Video Textures": "视频纹理",
    "Audio Effects": "音频特效",
    "Making a Simple Game - Part 4": "制作轻量游戏 - Part 4",
    "Terrain Generation from Heightmap": "从高程图创建地形",
    "Basic Mouse Input": "鼠标操作入门",
    "User Interface - Progress Bar": "",
    "Creating a Music Visualizer": "创建音乐可视化工具",
    "Light Halos": "光晕效果",
    "Custom Post Effects": "自定义后期特效",
    "Light Cookies": "灯光Cookies",
    "Using the Tween library": "",
    "User Interface - Stats Counter": "",
    "Entity Picking": "实体拾取",
    "Procedural Levels": "程序化关卡",
    "User Interface - Leaderboard": "",
    "Basic Keyboard Input": "键盘操作入门",
    "First Person Movement": "第一人称移动",
    "Real Time Multiplayer": "实时多人游戏",
    "Making a Simple Game - Part 1": "制作轻量游戏 - Part 1",
    "Basic Materials": "材质入门",
    "Collision and Triggers": "碰撞与触发器",
    "Tutorials": "教程",
    "Animation Blending": "动画混合",
    "Loading JSON Data": "读取 JSON 数据",
    "Custom Shaders": "自定义 shader",
    "User Interface - Buttons": "",
    "Making a Simple Game - Part 6": "制作轻量游戏 - Part 6",
    "Making a Simple Game - Part 3": "制作轻量游戏 - Part 3",
    "WebXR UI Interaction": "",
    "Using the Asset Registry": "使用资源注册",
    "Programmatically Creating Entities": "程序中创建实体"
}