{
    "PlayCanvas Engine": "PlayCanvas 引擎",
    "Oh No!": "糟糕!",
    "Getting Started": "快速入门",
    "PlayCanvas Developer Resources": "PlayCanvas 开发者资源",
    "Search - PlayCanvas Developer Resources": "搜索 - PlayCanvas 开发者资源",
    "Add a component": "添加组件",
    "Add a script": "添加脚本",
    "Change the background color": "修改背景颜色",
    "Change the color of a model": "修改模型颜色",
    "Create a cubemap": "创建Cubemap",
    "Create an Entity": "创建实体",
    "Create a light": "创建灯光",
    "Create a material": "创建材质",
    "Create a new shader": "创建 shader",
    "Create a shape like a box, sphere etc.": "创建形体（立方，球，其它）",
    "Create a skybox": "创建天空盒",
    "Delete an asset": "删除资源",
    "Delete an Entity": "删除实体",
    "Duplicate an Entity": "复制实体",
    "Play an animation": "播放动画",
    "Play a sound": "播放声音",
    "Remove a component": "移除组件",
    "Render a 3D model": "渲染 3D 模型",
    "Move / Rotate / Scale an Entity": "平移 / 旋转 / 缩放 实体",
    "Upload assets": "上传资源",
    "Use physics": "使用物理特性",
    "Use real-time shadows": "使用实时阴影",
    "Animated Textures": "动画纹理",
    "Animation Blending": "动画混合",
    "Audio Effects": "音频特效",
    "Basic Audio": "音频入门",
    "Basic Cameras": "摄影机入门",
    "Basic Materials": "材质入门",
    "Collision and Triggers": "碰撞与触发器",
    "Controlling Lights": "灯光管理",
    "Custom Post Effects": "自定义后期特效",
    "Custom Shaders": "自定义 shader",
    "Entity Picking": "实体拾取",
    "Facebook API": "Facebook API接口",
    "First Person Movement": "第一人称移动",
    "Tutorials": "教程",
    "Making a Simple Game - Part 5": "制作轻量游戏 - Part 5",
    "Making a Simple Game - Part 4": "制作轻量游戏 - Part 4",
    "Making a Simple Game - Part 1": "制作轻量游戏 - Part 1",
    "Making a Simple Game - Part 6": "制作轻量游戏 - Part 6",
    "Making a Simple Game - Part 3": "制作轻量游戏 - Part 3",
    "Making a Simple Game - Part 2": "制作轻量游戏 - Part 2",
    "Basic Keyboard Input": "键盘操作入门",
    "Light Cookies": "灯光Cookies",
    "Light Halos": "光晕效果",
    "Loading JSON Data": "读取 JSON 数据",
    "Manipulating Entities": "实体管理",
    "More Cameras": "多摄影机位",
    "Basic Mouse Input": "鼠标操作入门",
    "Creating a Music Visualizer": "创建音乐可视化工具",
    "Procedural Levels": "程序化关卡",
    "Programmatically Creating Entities": "程序中创建实体",
    "Real Time Multiplayer": "实时多人游戏",
    "Terrain Generation from Heightmap": "从高程图创建地形",
    "Using the Asset Registry": "使用资源注册",
    "Forces and Impulses": "力与冲量",
    "Video Textures": "视频纹理",
    "Creating an Account": "创建帐户",
    "Glossary": "词汇表",
    "User Manual": "用户手册",
    "Introduction": "简介",
    "Apps - Download app": "应用- 应用下载",
    "Apps - Get app": "应用- 获取应用",
    "Jobs - Get job": "职位- 获得职位",
    "Apps - Get primary app": "应用- 得到私有应用",
    "Apps - Get project apps": "应用- 获取项目应用",
    "REST API": "REST API",
    "Projects - Archive project": "项目 - 项目归类",
    "Animation": "动画",
    "Audio": "音频",
    "CSS": "CSS",
    "Cubemaps": "立方体贴图",
    "Finding Assets": "查找资源",
    "HTML": "HTML",
    "Asset Import Pipeline": "资源导入流程",
    "Uploading and Importing": "上传和导入",
    "Assets": "资源",
    "Materials": "材质",
    "Phong Material": "Phong 材质",
    "Physical Material": "物理学材质",
    "Preloading and Streaming": "预加载和流式加载",
    "Shader": "Shader",
    "Textures": "纹理",
    "Building Models": "制作模型",
    "Exporting Assets": "导出资源",
    "Models": "模型",
    "Units": "单位",
    "Dashboard Header": "指示板标题",
    "Dashboard": "指示板",
    "Overview": "总览",
    "Settings": "设置",
    "Asset Library": "资源库",
    "Hierarchy": "层级树",
    "Editor": "编辑器",
    "Inspector": "检查器",
    "Keyboard Shortcuts": "快捷键",
    "Loading Screen": "载入界面",
    "Menu and Toolbar": "菜单与工具栏",
    "Scenes": "场景",
    "Viewport": "视口",
    "Cameras": "摄影机",
    "File Format": "文件格式",
    "Graphics": "图形",
    "Particles": "粒子",
    "Lighting": "光照",
    "Lightmaps": "光照贴图",
    "Lights": "灯光",
    "Shadows": "阴影",
    "Physically Based Rendering": "物理学渲染",
    "Physical Materials": "物理学材质",
    "Bloom Effect": "Bloom 特效",
    "Brightness-Contrast Effect": "明暗-对比度 特效",
    "FXAA Effect": "FXAA 抗锯齿",
    "Hue-Saturation Effect": "色相-饱和度 特效",
    "Post Effects": "后处理特效",
    "Sepia Effect": "Sepia 特效",
    "Vignette Effect": "暗角特效",
    "Optimization Guidelines": "优化参考",
    "Performance": "性能",
    "Profiler": "分析器",
    "Troubleshooting Performance": "故障排除性能",
    "Creating Organizations": "创建组织",
    "Organizations": "组织",
    "Managing Organizations": "管理组织",
    "Audio Listener": "音频侦听器",
    "Camera": "摄影机",
    "Collision": "碰撞",
    "Components": "组件",
    "Light": "灯光",
    "Model": "模型",
    "Particle System": "粒子系统",
    "Rigid Body": "刚体",
    "Script": "脚本",
    "Sound": "声音",
    "Entities": "实体",
    "Physics": "物理",
    "Account": "账户",
    "Home": "首页",
    "Profile": "信息",
    "Projects": "项目",
    "Publishing": "发布",
    "Desktop": "桌面",
    "Cocoon": "Cocoon",
    "Firefox OS": "Firefox OS",
    "Mobile": "移动平台",
    "Intel XDK": "英特尔 XDK 跨平台集成开发环境",
    "Chrome Web Store": "谷歌浏览器商城",
    "Communication with web pages": "网页传输",
    "Facebook": "Facebook",
    "Hosting using a CDN": "使用CDN进行托管",
    "Web": "网页",
    "Kongregate": "Kongregate",
    "PlayCanvas Hosting": "PlayCanvas 服务",
    "Self-hosting for beginners": "面向初学者的自设服务器",
    "Self-hosting": "自设服务器",
    "Anatomy of a script": "脚本构造",
    "Code Editor": "编辑器",
    "Communication": "通信交互",
    "Creating new scripts": "创建新脚本",
    "Debugging": "调试",
    "Hot Reloading": "热点重加载",
    "Scripting": "脚本",
    "Loading Order": "加载顺序",
    "Script Attributes": "脚本特性",
    "Version Control": "版本控制",
    "Anatomy of a Script": "脚本构造",
    "Creating and attaching scripts": "创建和添加脚本",
    "Events": "事件",
    "Legacy Scripting": "常用脚本",
    "Script Priority": "脚本优先序",
    "Workflow": "工作流",
    "VR": "虚拟现实",
    "Optimizing WebVR applications": "优化WebVR应用程序",
    "Types of VR experiences": "VR体验的类型",
    "Using WebVR in PlayCanvas": "在PlayCanvas中使用WebVR"
}