{
    "PlayCanvas Engine": "PlayCanvas エンジン",
    "Oh No!": "問題が発生したら",
    "Getting Started": "始めてみよう",
    "PlayCanvas Developer Resources": "PlayCanvas 開発者リソース",
    "Search - PlayCanvas Developer Resources": "検索 - PlayCanvas 開発者リソース",
    "Add a component": "コンポーネントを追加",
    "Add a script": "スクリプトを追加",
    "Change the background color": "背景の色を変更",
    "Change the color of a model": "モデルの色を変更",
    "Create a cubemap": "キューブマップを作成",
    "Create an Entity": "エクスポートを作成",
    "Create a light": "ライトを作成",
    "Create a material": "素材を作成",
    "Create a new shader": "新しいシェーダーの作成",
    "Create a shape like a box, sphere etc.": "ボックスや球体などの形を作成",
    "Create a skybox": "スカイボックスを作成",
    "Delete an asset": "アセットを削除",
    "Delete an Entity": "エンティティを削除",
    "Duplicate an Entity": "エンティティを複製",
    "Play an animation": "アニメーションを再生",
    "Play a sound": "音声を再生",
    "Remove a component": "コンポーネントを取り除く",
    "Render a 3D model": "3Dモデルをレンダリング",
    "Move / Rotate / Scale an Entity": "エンティティを動かす／回転する／スケールする",
    "Upload assets": "アセットをアップロード",
    "Use physics": "物理の使用",
    "Use real-time shadows": "リアルタイムシャドーを使用",
    "Animated Textures": "アニメーション化したテクスチャー",
    "Animation Blending": "アニメーションのブレンディング",
    "Audio Effects": "音声エフェクト",
    "Basic Audio": "基本的なオーディオ",
    "Basic Cameras": "基本的なカメラ",
    "Basic Materials": "基本的な素材",
    "Collision and Triggers": "コリジョン及びトリガー",
    "Controlling Lights": "ライトのコントロール",
    "Custom Post Effects": "カスタムの後処理エフェクト",
    "Custom Shaders": "カスタムのシェーダー",
    "Entity Picking": "エンティティの選択",
    "Facebook API": "Facebook API",
    "First Person Movement": "ファーストパーソンの動作",
    "Tutorials": "チュートリアル",
    "Making a Simple Game - Part 5": "シンプルなゲームの作成 - パート5",
    "Making a Simple Game - Part 4": "シンプルなゲームの作成 - パート4",
    "Making a Simple Game - Part 1": "シンプルなゲームの作成 - パート1",
    "Making a Simple Game - Part 6": "シンプルなゲームの作成 - パート6",
    "Making a Simple Game - Part 3": "シンプルなゲームの作成 - パート3",
    "Making a Simple Game - Part 2": "シンプルなゲームの作成 - パート2",
    "Basic Keyboard Input": "基本的なキーボード入力",
    "Light Cookies": "ライトクッキー",
    "Light Halos": "ライト Halo",
    "Loading JSON Data": "JSONデータの読み込み",
    "Manipulating Entities": "エンティティの操作",
    "More Cameras": "その他のカメラ",
    "Basic Mouse Input": "基本的なマウス入力",
    "Creating a Music Visualizer": "音楽ビジュアライザーの作成",
    "Procedural Levels": "プロシージャルレベル",
    "Programmatically Creating Entities": "プログラムでエフェクトを作成",
    "Real Time Multiplayer": "リアルタイムマルチプレイヤー",
    "Terrain Generation from Heightmap": "ハイトマップから地形形成",
    "Using the Asset Registry": "アセットレジストリを使用",
    "Forces and Impulses": "動力および衝撃",
    "Video Textures": "ビデオテクスチャー",
    "Creating an Account": "",
    "Glossary": "用語集",
    "User Manual": "ユーザーマニュアル",
    "Introduction": "はじめに",
    "Apps - Download app": "Apps - appのダウンロード",
    "Apps - Get app": "Apps - appの取得",
    "Jobs - Get job": "Jobs - jobを取得",
    "Apps - Get primary app": "Apps - プライマリappを取得",
    "Apps - Get project apps": "Apps - プロジェクトappの取得",
    "REST API": "REST API",
    "Animation": "アニメーション",
    "Audio": "オーディオ",
    "CSS": "CSS",
    "Cubemaps": "",
    "Finding Assets": "アセットを探す",
    "HTML": "HTML",
    "Asset Import Pipeline": "アセットインポートのパイプライン",
    "Uploading and Importing": "アップロードとインポート",
    "Assets": "アセット",
    "Materials": "素材",
    "Phong Material": "Phong素材",
    "Physical Material": "物理的な素材",
    "Preloading and Streaming": "プレロード及びストリーミング",
    "Shader": "シェーダー",
    "Textures": "テクスチャー",
    "Building Models": "モデルの構築",
    "Exporting Assets": "アセットのエキスポート",
    "Models": "",
    "Units": "単位",
    "Dashboard Header": "ダッシュボードヘッダー",
    "Dashboard": "ダッシュボード",
    "Overview": "概要",
    "Settings": "設定",
    "Asset Library": "アセットライブラリ",
    "Hierarchy": "階層",
    "Editor": "エディタ",
    "Inspector": "インスペクター",
    "Keyboard Shortcuts": "キーボードショートカット",
    "Loading Screen": "画面の読み込み",
    "Menu and Toolbar": "メニューとツールバー",
    "Scenes": "シーン",
    "Viewport": "ビューポート",
    "Cameras": "カメラ",
    "File Format": "ファイル形式",
    "Graphics": "グラフィック",
    "Particles": "パーティクル",
    "Lighting": "ライティング",
    "Lightmaps": "ライトマップ",
    "Lights": "ライト",
    "Shadows": "影",
    "Physically Based Rendering": "物理ベースのレンダリング",
    "Physical Materials": "物理素材",
    "Bloom Effect": "Bloom エフェクト",
    "Brightness-Contrast Effect": "明るさ-コントラスト エフェクト",
    "FXAA Effect": "FXAA エフェクト",
    "Hue-Saturation Effect": "色相-彩度 エフェクト",
    "Post Effects": "後処理エフェクト",
    "Sepia Effect": "セピアエフェクト",
    "Vignette Effect": "ビネットエフェクト",
    "Optimization Guidelines": "最適化のガイドライン",
    "Performance": "",
    "Profiler": "プロファイラー",
    "Troubleshooting Performance": "",
    "Creating Organizations": "組織の作成",
    "Organizations": "組織",
    "Managing Organizations": "組織の管理",
    "Audio Listener": "オーディオリスナー",
    "Camera": "カメラ",
    "Collision": "コリジョン",
    "Components": "コンポーネント",
    "Light": "ライト",
    "Model": "モデル",
    "Particle System": "パーティクルシステム",
    "Rigid Body": "リジッドボディ",
    "Script": "スクリプト",
    "Sound": "サウンド",
    "Entities": "エンティティ",
    "Physics": "物理",
    "Account": "アカウント",
    "Home": "ホーム",
    "Profile": "プロフィール",
    "Projects": "プロジェクト",
    "Publishing": "公開",
    "Desktop": "デスクトップ",
    "Cocoon": "Cocoon",
    "Firefox OS": "Firefox OS",
    "Mobile": "モバイル",
    "Intel XDK": "Intel XDK",
    "Chrome Web Store": "Chrome ウェブストア",
    "Communication with web pages": "ウェブページとの通信",
    "Facebook": "Facebook",
    "Hosting using a CDN": "CDNを使用してホスティング",
    "Web": "ウェブ",
    "Kongregate": "Kongregate",
    "PlayCanvas Hosting": "PlayCanvas ホスティング",
    "Self-hosting for beginners": "初心者のためのセルフホスティング",
    "Self-hosting": "セルフホスティング",
    "Anatomy of a script": "スクリプトの構造",
    "Code Editor": "コードエディタ",
    "Communication": "コミュニケーション",
    "Creating new scripts": "新しいスクリプトの作成",
    "Debugging": "デバッグ",
    "Hot Reloading": "Hot リロード",
    "Scripting": "スクリプティング",
    "Loading Order": "読み込みの順番",
    "Script Attributes": "スクリプト属性",
    "Version Control": "バージョンの管理",
    "Anatomy of a Script": "スクリプトの構造",
    "Creating and attaching scripts": "スクリプトの作成と添付",
    "Events": "イベント",
    "Legacy Scripting": "レガシーのスクリプティング",
    "Script Priority": "スクリプトのプライオリティ",
    "Workflow": "ワークフロー",
    "VR": "",
    "Optimizing WebVR applications": "",
    "Types of VR experiences": "",
    "Using WebVR in PlayCanvas": ""
}