{
    "Search - PlayCanvas Developer Resources": "検索 - PlayCanvas 開発者リソース",
    "Oh No!": "問題が発生したら",
    "PlayCanvas Developer Resources": "PlayCanvas 開発者リソース",
    "Introduction": "はじめに",
    "Shader Editor": "",
    "Info Pane": "",
    "Nodes Pane": "",
    "Graph Editor": "",
    "Preview Pane": "",
    "Window Layout": "",
    "Assets Pane": "",
    "Texture Inspector": "",
    "Graph Inspector": "",
    "Inspector Pane": "",
    "Material Inspector": "",
    "Node Inspector": "",
    "Textures": "テクスチャー",
    "Workflow": "ワークフロー",
    "Overview": "概要",
    "File Handling": "",
    "Materials": "素材",
    "Nodes": "",
    "Parameter Nodes": "",
    "Sub Graphs": "",
    "Graphs": "",
    "Material Graphs": "",
    "Render a 3D model": "3Dモデルをレンダリング",
    "Play a sound": "音声を再生",
    "Create a cubemap": "キューブマップを作成",
    "Delete an Entity": "エンティティを削除",
    "Duplicate an Entity": "エンティティを複製",
    "Move / Rotate / Scale an Entity": "エンティティを動かす／回転する／スケールする",
    "Create a new shader": "新しいシェーダーの作成",
    "Play an animation": "アニメーションを再生",
    "Create a skybox": "スカイボックスを作成",
    "Create a shape like a box, sphere etc.": "ボックスや球体などの形を作成",
    "Add a script": "スクリプトを追加",
    "Change the background color": "背景の色を変更",
    "Use real-time shadows": "リアルタイムシャドーを使用",
    "Use physics": "物理の使用",
    "Delete an asset": "アセットを削除",
    "Upload assets": "アセットをアップロード",
    "Create an Entity": "エクスポートを作成",
    "Add a component": "コンポーネントを追加",
    "Create a material": "素材を作成",
    "Change the material of a model": "",
    "Create a light": "ライトを作成",
    "Remove a component": "コンポーネントを取り除く",
    "Glossary": "用語集",
    "User Manual": "ユーザーマニュアル",
    "Made with PlayCanvas": "",
    "Your First App": "",
    "Creating an Account": "アカウントの作成",
    "Creating Organizations": "組織の作成",
    "Organizations": "組織",
    "Managing Organizations": "組織の管理",
    "Publishing": "公開",
    "Self-hosting": "セルフホスティング",
    "Facebook": "Facebook",
    "PlayCanvas Hosting": "PlayCanvas ホスティング",
    "Hosting using a CDN": "CDNを使用してホスティング",
    "Self-hosting for beginners": "初心者のためのセルフホスティング",
    "Communication with web pages": "ウェブページとの通信",
    "Web": "ウェブ",
    "Desktop": "デスクトップ",
    "Mobile": "モバイル",
    "Apache Cordova": "",
    "Facebook Playable Ad": "",
    "Snapchat Playable Ad": "",
    "ironSource Playable Ad (MRAID)": "",
    "Playable Ads": "",
    "Engine-Only Users": "",
    "Code Editor": "コードエディタ",
    "Communication": "コミュニケーション",
    "Migration Guide": "",
    "Loading Order": "読み込みの順番",
    "Scripting": "スクリプティング",
    "Script Attributes": "スクリプト属性",
    "Using a Custom Engine": "",
    "Hot Reloading": "Hot リロード",
    "Debugging": "デバッグ",
    "Creating new scripts": "新しいスクリプトの作成",
    "Anatomy of a script": "スクリプトの構造",
    "Optimize Scene Format": "",
    "Device Pixel Ratio": "",
    "Optimization Guidelines": "最適化のガイドライン",
    "Hardware Instancing": "",
    "Profiler": "プロファイラー",
    "Mini Stats": "",
    "Performance": "パフォーマンス",
    "Batching": "",
    "Optimizing Load Time": "",
    "Troubleshooting Performance": "トラブルシューティングのパフォーマンス",
    "Merging and resolving conflicts": "",
    "Branches": "",
    "Version Control": "バージョンの管理",
    "View Changes": "",
    "Branch Workflows": "",
    "Checkpoints": "",
    "Animation Assets": "",
    "Anim Events": "",
    "Anim Layer Masks": "",
    "Animstategraph Assets": "",
    "Animation": "アニメーション",
    "Anim Component": "",
    "Optimizing WebXR applications": "",
    "Types of XR experiences": "",
    "XR": "",
    "Using WebXR in PlayCanvas": "",
    "WebXR Input Sources in PlayCanvas": "",
    "User Interface Basics": "ユーザインターフェイスの基本",
    "Input": "入力",
    "Text Elements": "テキスト要素",
    "Safe Area": "",
    "Localization": "",
    "Image Elements": "イメージ要素",
    "Screens": "画面",
    "User Interface": "ユーザインターフェース",
    "Layout Groups": "",
    "Elements": "要素",
    "Group Elements": "グループ要素",
    "Scenes": "シーン",
    "Layout Group": "",
    "Layout Child": "",
    "Particle System": "パーティクルシステム",
    "Sprite": "",
    "Model": "モデル",
    "Scrollview": "",
    "Button": "",
    "Camera": "カメラ",
    "Scrollbar": "",
    "Script": "スクリプト",
    "Anim": "",
    "Render": "",
    "Light": "ライト",
    "Components": "コンポーネント",
    "Sound": "サウンド",
    "Screen": "画面",
    "Audio Listener": "オーディオリスナー",
    "Element": "要素",
    "Collision": "コリジョン",
    "Rigid Body": "リジッドボディ",
    "Entities": "エンティティ",
    "Settings": "設定",
    "Dashboard Header": "ダッシュボードヘッダー",
    "Dashboard": "ダッシュボード",
    "Account": "アカウント",
    "Projects": "プロジェクト",
    "Home": "ホーム",
    "Profile": "プロフィール",
    "Assets": "アセット",
    "Editor API": "",
    "Menu and Toolbar": "メニューとツールバー",
    "Viewport": "ビューポート",
    "Keyboard Shortcuts": "キーボードショートカット",
    "Asset Library": "アセットライブラリ",
    "Loading Screen": "画面の読み込み",
    "Editor": "エディタ",
    "Inspector": "インスペクター",
    "Hierarchy": "階層",
    "Assets - Get Asset File": "",
    "Projects - Archive project": "プロジェクト - プロジェクトのアーカイブ",
    "Assets - Update asset": "",
    "Assets - Delete asset": "",
    "Assets - Create asset": "",
    "Assets - Get Asset": "",
    "Apps - Get primary app": "Apps - プライマリappを取得",
    "Branches - List branches": "",
    "REST API": "REST API",
    "Apps - Get app": "Apps - appの取得",
    "Jobs - Get job": "Jobs - jobを取得",
    "Assets - List assets": "",
    "Apps - Get project apps": "Apps - プロジェクトappの取得",
    "Apps - Download app": "Apps - appのダウンロード",
    "Scenes - List scenes": "",
    "Override Diff View": "",
    "Nested Templates": "",
    "Templates": "",
    "Alternatives to ammo.js": "",
    "Ray Casting": "",
    "Physics": "物理",
    "Trigger Volumes": "",
    "Updating ammo.js": "",
    "Forces and Impulses": "動力および衝撃",
    "Calling the ammo.js API": "",
    "Physics Basics": "",
    "Cameras": "カメラ",
    "File Format": "ファイル形式",
    "Particles": "パーティクル",
    "Graphics": "グラフィック",
    "Layers": "",
    "Physical Materials": "物理素材",
    "Image Based Lighting": "イメージベースの照明",
    "Physically Based Rendering": "物理ベースのレンダリング",
    "Shadows": "影",
    "Lightmapping": "ライトマッピング",
    "Ambient Occlusion": "アンビエントオクルージョン",
    "Lights": "ライト",
    "Lighting": "ライティング",
    "Runtime Lightmaps": "ランタイムライトマップ",
    "FXAA Effect": "FXAA エフェクト",
    "Bloom Effect": "Bloom エフェクト",
    "Vignette Effect": "ビネットエフェクト",
    "Hue-Saturation Effect": "色相-彩度 エフェクト",
    "Brightness-Contrast Effect": "明るさ-コントラスト エフェクト",
    "Post Effects": "後処理エフェクト",
    "Sepia Effect": "セピアエフェクト",
    "CSS": "CSS",
    "Template": "",
    "Texture Atlas": "",
    "Preloading and Streaming": "プレロード及びストリーミング",
    "Audio": "オーディオ",
    "Font": "",
    "Cubemap": "",
    "Shader": "シェーダー",
    "Uploading and Importing": "アップロードとインポート",
    "Finding Assets": "アセットを探す",
    "Wasm Module": "",
    "HTML": "HTML",
    "Texture Compression": "",
    "Texture": "",
    "Material": "",
    "Phong Material": "Phong素材",
    "Physical Material": "物理的な素材",
    "Exporting Assets": "アセットのエキスポート",
    "Units": "単位",
    "Building Models": "モデルの構築",
    "Asset Import Pipeline": "アセットインポートのパイプライン",
    "Import Hierarchy": "",
    "9-slicing": "",
    "2D": "",
    "Sprite Editor": "",
    "Billing": "",
    "Basic Audio": "基本的なオーディオ",
    "Facebook API": "Facebook API",
    "Manipulating Entities": "エンティティの操作",
    "Making a Simple Game - Part 2": "シンプルなゲームの作成 - パート2",
    "Making a Simple Game - Part 5": "シンプルなゲームの作成 - パート5",
    "Animated Textures": "アニメーション化したテクスチャー",
    "Basic Cameras": "基本的なカメラ",
    "More Cameras": "その他のカメラ",
    "Controlling Lights": "ライトのコントロール",
    "Anim State Graph Blending": "",
    "Video Textures": "ビデオテクスチャー",
    "Audio Effects": "音声エフェクト",
    "Making a Simple Game - Part 4": "シンプルなゲームの作成 - パート4",
    "Terrain Generation from Heightmap": "ハイトマップから地形形成",
    "Basic Mouse Input": "基本的なマウス入力",
    "User Interface - Progress Bar": "ユーザインターフェイス - 進行バー",
    "Creating a Music Visualizer": "音楽ビジュアライザーの作成",
    "Light Halos": "ライト Halo",
    "Custom Post Effects": "カスタムの後処理エフェクト",
    "Light Cookies": "ライトクッキー",
    "Using the Tween library": "Tweenライブラリの使用",
    "User Interface - Stats Counter": "ユーザインターフェイス - 統計カウンター",
    "Entity Picking": "エンティティの選択",
    "Procedural Levels": "プロシージャルレベル",
    "User Interface - Leaderboard": "ユーザインターフェイス - リーダーボード",
    "Basic Keyboard Input": "基本的なキーボード入力",
    "First Person Movement": "ファーストパーソンの動作",
    "Real Time Multiplayer": "リアルタイムマルチプレイヤー",
    "Making a Simple Game - Part 1": "シンプルなゲームの作成 - パート1",
    "Basic Materials": "基本的な素材",
    "Collision and Triggers": "コリジョン及びトリガー",
    "Tutorials": "チュートリアル",
    "Animation Blending": "アニメーションのブレンディング",
    "Loading JSON Data": "JSONデータの読み込み",
    "Custom Shaders": "カスタムのシェーダー",
    "User Interface - Buttons": "ユーザインターフェイス - ボタン",
    "Making a Simple Game - Part 6": "シンプルなゲームの作成 - パート6",
    "Making a Simple Game - Part 3": "シンプルなゲームの作成 - パート3",
    "WebXR UI Interaction": "",
    "Using the Asset Registry": "アセットレジストリを使用",
    "Programmatically Creating Entities": "プログラムでエフェクトを作成"
}