{
    "PlayCanvas Engine": "PlayCanvas エンジン",
    "Oh No!": "問題が発生したら",
    "Getting Started": "始めてみよう",
    "PlayCanvas Developer Resources": "PlayCanvas 開発者リソース",
    "Search - PlayCanvas Developer Resources": "検索 - PlayCanvas 開発者リソース",
    "Add a component": "コンポーネントを追加",
    "Add a script": "スクリプトを追加",
    "Change the background color": "背景の色を変更",
    "Change the color of a model": "モデルの色を変更",
    "Create a cubemap": "キューブマップを作成",
    "Create an Entity": "エクスポートを作成",
    "Create a light": "ライトを作成",
    "Create a material": "素材を作成",
    "Create a new shader": "",
    "Create a shape like a box, sphere etc.": "ボックスや球体などの形を作成",
    "Create a skybox": "スカイボックスを作成",
    "Delete an asset": "アセットを削除",
    "Delete an Entity": "エンティティを削除",
    "Duplicate an Entity": "エンティティを複製",
    "Play an animation": "アニメーションを再生",
    "Play a sound": "音声を再生",
    "Remove a component": "コンポーネントを取り除く",
    "Render a 3D model": "3Dモデルをレンダリング",
    "Move / Rotate / Scale an Entity": "エンティティを動かす／回転する／スケールする",
    "Upload assets": "アセットをアップロード",
    "Use physics": "物理の使用",
    "Use real-time shadows": "リアルタイムシャドーを使用",
    "Tutorials": "チュートリアル",
    "Audio Effects": "",
    "Custom Post Effects": "カスタムの後処理エフェクト",
    "Custom Shaders": "カスタムのシェーダー",
    "Advanced": "上級",
    "Plasma Shader": "プラズマシェーダー",
    "Programmatically Creating Entities": "プログラムでエフェクトを作成",
    "Real Time Multiplayer": "",
    "Terrain Generation from Heightmap": "ハイトマップから地形形成",
    "Basic Audio": "基本的なオーディオ",
    "Basic Cameras": "基本的なカメラ",
    "Basic Materials": "基本的な素材",
    "Cardboard VR": "",
    "Controlling Lights": "ライトのコントロール",
    "Beginners": "初級",
    "Making a Simple Game - Part 5": "",
    "Making a Simple Game - Part 4": "",
    "Making a Simple Game - Part 1": "",
    "Making a Simple Game - Part 6": "",
    "Making a Simple Game - Part 3": "",
    "Making a Simple Game - Part 2": "",
    "Basic Keyboard Input": "基本的なキーボード入力",
    "Loading JSON Data": "JSONデータの読み込み",
    "Manipulating Entities": "エンティティの操作",
    "Basic Mouse Input": "基本的なマウス入力",
    "Forces and Impulses": "動力および衝撃",
    "Animated Textures": "",
    "Animation Blending": "アニメーションのブレンディング",
    "Collision and Triggers": "コリジョン及びトリガー",
    "Entity Picking": "エンティティの選択",
    "Facebook API": "",
    "First Person Movement": "ファーストパーソンの動作",
    "Intermediate": "中級",
    "Light Cookies": "",
    "Light Halos": "",
    "More Cameras": "その他のカメラ",
    "Creating a Music Visualizer": "",
    "Procedural Levels": "プロシージャルレベル",
    "Using the Asset Registry": "アセットレジストリを使用",
    "Video Textures": "ビデオテクスチャー",
    "Video Tutorials": "動画チュートリアル",
    "Glossary": "用語集",
    "User Manual": "ユーザーマニュアル",
    "Introduction": "はじめに",
    "Apps - Download app": "",
    "Apps - Get app": "",
    "Jobs - Get job": "",
    "Apps - Get primary app": "",
    "Apps - Get project apps": "",
    "REST API": "",
    "Animation": "アニメーション",
    "Audio": "オーディオ",
    "CSS": "CSS",
    "Cube Maps": "キューブマップ",
    "Finding Assets": "アセットを探す",
    "HTML": "HTML",
    "Asset Import Pipeline": "",
    "Uploading and Importing": "アップロードとインポート",
    "Assets": "アセット",
    "Materials": "素材",
    "Phong Material": "Phong素材",
    "Physical Material": "物理的な素材",
    "Preloading and Streaming": "プレロード及びストリーミング",
    "Shader": "シェーダー",
    "Textures": "テクスチャー",
    "Building Models": "モデルの構築",
    "Exporting Assets": "アセットのエキスポート",
    "Scenes and Models": "シーンとモデル",
    "Units": "",
    "Dashboard Header": "ダッシュボードヘッダー",
    "Dashboard": "ダッシュボード",
    "Overview": "概要",
    "Settings": "設定",
    "Asset Library": "アセットライブラリ",
    "Hierarchy": "階層",
    "Editor": "エディタ",
    "Inspector": "インスペクター",
    "Keyboard Shortcuts": "キーボードショートカット",
    "Loading Screen": "画面の読み込み",
    "Menu and Toolbar": "メニューとツールバー",
    "Scenes": "シーン",
    "Viewport": "ビューポート",
    "Cameras": "カメラ",
    "File Format": "",
    "Graphics": "グラフィック",
    "Particles": "パーティクル",
    "Lighting": "",
    "Lightmaps": "",
    "Lights": "ライト",
    "Shadows": "影",
    "Physically Based Rendering": "物理ベースのレンダリング",
    "Physical Materials": "物理素材",
    "Bloom Effect": "Bloom エフェクト",
    "Brightness-Contrast Effect": "明るさ-コントラスト エフェクト",
    "FXAA Effect": "FXAA エフェクト",
    "Hue-Saturation Effect": "色相-彩度 エフェクト",
    "Post Effects": "後処理エフェクト",
    "Sepia Effect": "セピアエフェクト",
    "Vignette Effect": "ビネットエフェクト",
    "Optimization Guidelines": "",
    "Optimization": "",
    "Profiler": "",
    "Creating Organizations": "",
    "Organizations": "",
    "Managing Organizations": "",
    "Audio Listener": "オーディオリスナー",
    "Camera": "カメラ",
    "Collision": "コリジョン",
    "Components": "コンポーネント",
    "Light": "ライト",
    "Model": "モデル",
    "Particle System": "パーティクルシステム",
    "Rigid Body": "リジッドボディ",
    "Script": "スクリプト",
    "Sound": "",
    "Entities": "エンティティ",
    "Physics": "物理",
    "Account": "アカウント",
    "Home": "ホーム",
    "Profile": "プロフィール",
    "Projects": "プロジェクト",
    "Publishing": "公開",
    "Desktop": "デスクトップ",
    "Cocoon": "Cocoon",
    "Firefox OS": "Firefox OS",
    "Mobile": "モバイル",
    "Intel XDK": "Intel XDK",
    "Chrome Web Store": "Chrome ウェブストア",
    "Communication with web pages": "",
    "Facebook": "",
    "Web": "ウェブ",
    "Kongregate": "",
    "PlayCanvas Hosting": "PlayCanvas ホスティング",
    "Self-hosting for beginners": "",
    "Self-hosting": "セルフホスティング",
    "Anatomy of a script": "",
    "Code Editor": "",
    "Communication": "コミュニケーション",
    "Creating new scripts": "",
    "Debugging": "デバッグ",
    "Hot Reloading": "",
    "Scripting": "スクリプティング",
    "Loading Order": "",
    "Script Attributes": "スクリプト属性",
    "Version Control": "",
    "Anatomy of a Script": "スクリプトの構造",
    "Creating and attaching scripts": "スクリプトの作成と添付",
    "Events": "イベント",
    "Legacy Scripting": "",
    "Script Priority": "",
    "Workflow": "ワークフロー"
}