{
    "PlayCanvas Engine": "Движок PlayCanvas",
    "Oh No!": "О нет!",
    "Getting Started": "Для начала",
    "PlayCanvas Developer Resources": "Ресурсы разработчика PlayCanvas",
    "Search - PlayCanvas Developer Resources": "Поиск - ресурсы разработчика PlayCanvas",
    "Add a component": "Добавить компонент",
    "Add a script": "Добавить скрипт",
    "Change the background color": "Изменить задний фон",
    "Change the color of a model": "Изменить цвет модели",
    "Create a cubemap": "Создать кубическую текстуру",
    "Create an Entity": "Создать сущность",
    "Create a light": "Создать свет",
    "Create a material": "Создать материал",
    "Create a new shader": "Создать новый шейдер",
    "Create a shape like a box, sphere etc.": "Создать примитивы, такие как куб, сфера и т.д.",
    "Create a skybox": "Создать скайбокс",
    "Delete an asset": "Удалить ресурс",
    "Delete an Entity": "Удалить сущность",
    "Duplicate an Entity": "Дублировать сущность",
    "Play an animation": "Воспроизвести анимацию",
    "Play a sound": "Воспроизвести звук",
    "Remove a component": "Удалить компонент",
    "Render a 3D model": "Отобразить 3D модель",
    "Move / Rotate / Scale an Entity": "Переместить / Повернуть / Масштабировать сущность",
    "Upload assets": "Загрузить ресурсы",
    "Use physics": "Использовать физику",
    "Use real-time shadows": "Использовать затенение в реальном времени",
    "Animated Textures": "Анимированные текстуры",
    "Animation Blending": "Смешивание анимаций",
    "Audio Effects": "",
    "Basic Audio": "Основы об аудио",
    "Basic Cameras": "Основы камер",
    "Basic Materials": "Основы материалов",
    "Collision and Triggers": "Столкновения и триггеры",
    "Controlling Lights": "Контроль света",
    "Custom Post Effects": "Пользовательские пост-эффекты",
    "Custom Shaders": "Пользовательские шейдеры",
    "Entity Picking": "Выбор сущностей",
    "Facebook API": "Facebook API",
    "First Person Movement": "Модель движения шутера от первого лица",
    "Tutorials": "Уроки",
    "Making a Simple Game - Part 5": "Создание простой игры - Часть 5",
    "Making a Simple Game - Part 4": "Создание простой игры - Часть 4",
    "Making a Simple Game - Part 1": "Создание простой игры - Часть 1",
    "Making a Simple Game - Part 6": "Создание простой игры - Часть 6",
    "Making a Simple Game - Part 3": "Создание простой игры - Часть 3",
    "Making a Simple Game - Part 2": "Создание простой игры - Часть 2",
    "Basic Keyboard Input": "Основы ввода с клавиатуры",
    "Light Cookies": "Запекание света",
    "Light Halos": "Отблески света",
    "Loading JSON Data": "Загрузка информации в JSON",
    "Manipulating Entities": "Манипуляции с объектами",
    "More Cameras": "Больше о камерах",
    "Basic Mouse Input": "Основы управления мышью",
    "Creating a Music Visualizer": "Создание музыкального визуализатора",
    "Procedural Levels": "",
    "Programmatically Creating Entities": "Программное создание сущностей",
    "Real Time Multiplayer": "Многопользовательская игра",
    "Terrain Generation from Heightmap": "Генерация ландшафта из карты высот",
    "Using the Asset Registry": "Использование реестра ассетов",
    "Forces and Impulses": "Силы и импульсы",
    "Video Textures": "Видео-текстуры",
    "Creating an Account": "Создание аккаунта",
    "Glossary": "Глоссарий",
    "User Manual": "Руководство пользователя",
    "Introduction": "Введение",
    "Apps - Download app": "Приложение - загрузка приложений",
    "Apps - Get app": "Приложения - получить приложение",
    "Jobs - Get job": "Работа - получить работу",
    "Apps - Get primary app": "Приложения - получить основное приложение",
    "Apps - Get project apps": "Приложения - получить проекты приложений",
    "REST API": "REST API",
    "Animation": "Анимация",
    "Audio": "Аудио",
    "CSS": "Таблицы стилей CSS",
    "Cubemaps": "Кубические текстуры",
    "Finding Assets": "Поиск ассетов",
    "HTML": "HTML",
    "Asset Import Pipeline": "Процесс импорта ресурсов",
    "Uploading and Importing": "Загрузка и импорт",
    "Assets": "Ассеты",
    "Materials": "Материалы",
    "Phong Material": "Затенение по Фонгу",
    "Physical Material": "Физические материалы",
    "Preloading and Streaming": "Предзагрузка и стриминг",
    "Shader": "Шейдер",
    "Textures": "Текстуры",
    "Building Models": "Построение моделей",
    "Exporting Assets": "Экспорт ассетов",
    "Models": "Модели",
    "Units": "Юниты",
    "Dashboard Header": "Заголовок панели",
    "Dashboard": "Панель",
    "Overview": "Обзор",
    "Settings": "Настройки",
    "Asset Library": "Библиотека ассетов",
    "Hierarchy": "Иерархия",
    "Editor": "Редактора",
    "Inspector": "Инспектор",
    "Keyboard Shortcuts": "Горячие клавиши",
    "Loading Screen": "Загрузочный экран",
    "Menu and Toolbar": "Меню и панель инструментов",
    "Scenes": "Сцены",
    "Viewport": "Вид",
    "Cameras": "Камыр",
    "File Format": "Формат файла",
    "Graphics": "Графика",
    "Particles": "Частицы",
    "Lighting": "Освещение",
    "Lightmaps": "Карты теней",
    "Lights": "Источники света",
    "Shadows": "Тени",
    "Physically Based Rendering": "Отображение, основанное на физических свойствах",
    "Physical Materials": "Физические материалы",
    "Bloom Effect": "Bloom эффект",
    "Brightness-Contrast Effect": "Эффект яркости-контрастности",
    "FXAA Effect": "FXAA сглаживание",
    "Hue-Saturation Effect": "Эффект тона-насыщенности",
    "Post Effects": "Постэффекты",
    "Sepia Effect": "Эффект сепия",
    "Vignette Effect": "Эффект виньетки",
    "Optimization Guidelines": "Правила оптимизации",
    "Performance": "Производительность",
    "Profiler": "Профилировщик",
    "Troubleshooting Performance": "Проблемы с производительностью",
    "Creating Organizations": "Создание организаций",
    "Organizations": "Организации",
    "Managing Organizations": "Управление организациями",
    "Audio Listener": "Аудио слушатель",
    "Camera": "Камера",
    "Collision": "Столкновение",
    "Components": "Компоненты",
    "Light": "Свет",
    "Model": "Модель",
    "Particle System": "Система частиц",
    "Rigid Body": "Твёрдое тело",
    "Script": "Сценарий",
    "Sound": "Звук",
    "Entities": "Сущности",
    "Physics": "Физика",
    "Account": "Аккаунт",
    "Home": "Дом",
    "Profile": "Профиль",
    "Projects": "Проекты",
    "Publishing": "Публикация",
    "Desktop": "Рабочий стол",
    "Cocoon": "Cocoon",
    "Firefox OS": "Firefox OS",
    "Mobile": "Мобильный",
    "Intel XDK": "Intel XDK",
    "Chrome Web Store": "Веб магазин Chrome",
    "Communication with web pages": "Связь с веб-страницами",
    "Facebook": "Facebook",
    "Hosting using a CDN": "Хостинг с использованием CDN",
    "Web": "Веб",
    "Kongregate": "Kongregate",
    "PlayCanvas Hosting": "Хостинг PlayCanvas",
    "Self-hosting for beginners": "Самостоятельный хостинг для начинающих",
    "Self-hosting": "Свой хостинг",
    "Anatomy of a script": "Структура скрипта",
    "Code Editor": "Редактор кода",
    "Communication": "Связь",
    "Creating new scripts": "Создание новых скриптов",
    "Debugging": "Отладка",
    "Hot Reloading": "Горячая перезагрузка",
    "Scripting": "Написание сценариев",
    "Loading Order": "Очень загрузки",
    "Script Attributes": "Атрибуты сценария",
    "Version Control": "Контроль версии",
    "Anatomy of a Script": "Анатомия сценария",
    "Creating and attaching scripts": "Создание и привязка сценариев",
    "Events": "События",
    "Legacy Scripting": "Наследование скриптов",
    "Script Priority": "Приоритет скриптов",
    "Workflow": "Рабочий процесс",
    "VR": "VR",
    "Optimizing WebVR applications": "Оптимизация приложений WebVR ",
    "Types of VR experiences": "Типы VR",
    "Using WebVR in PlayCanvas": "Использование WebVR в PlayCanvas"
}