{
    "PlayCanvas Engine": "Движок PlayCanvas",
    "Oh No!": "О нет!",
    "Getting Started": "Для начала",
    "PlayCanvas Developer Resources": "Ресурсы разработчика PlayCanvas",
    "Search - PlayCanvas Developer Resources": "Поиск - ресурсы разработчика PlayCanvas",
    "Add a component": "",
    "Add a script": "",
    "Change the background color": "",
    "Change the color of a model": "",
    "Create a cubemap": "",
    "Create an Entity": "",
    "Create a light": "",
    "Create a material": "",
    "Create a new shader": "",
    "Create a shape like a box, sphere etc.": "",
    "Create a skybox": "",
    "Delete an asset": "",
    "Delete an Entity": "",
    "Duplicate an Entity": "",
    "Play an animation": "",
    "Play a sound": "",
    "Remove a component": "",
    "Render a 3D model": "",
    "Move / Rotate / Scale an Entity": "",
    "Upload assets": "",
    "Use physics": "",
    "Use real-time shadows": "",
    "Tutorials": "Уроки",
    "Audio Effects": "",
    "Custom Post Effects": "Пользовательские пост-эффекты",
    "Custom Shaders": "Пользовательские шейдеры",
    "Advanced": "Продвинутый",
    "Plasma Shader": "",
    "Programmatically Creating Entities": "Программное создание сущностей",
    "Real Time Multiplayer": "",
    "Terrain Generation from Heightmap": "",
    "Basic Audio": "Основы об аудио",
    "Basic Cameras": "Основы камер",
    "Basic Materials": "Основы материалов",
    "Cardboard VR": "",
    "Controlling Lights": "Контроль света",
    "Beginners": "Начинающие",
    "Making a Simple Game - Part 5": "",
    "Making a Simple Game - Part 4": "",
    "Making a Simple Game - Part 1": "",
    "Making a Simple Game - Part 6": "",
    "Making a Simple Game - Part 3": "",
    "Making a Simple Game - Part 2": "",
    "Basic Keyboard Input": "Основы ввода с клавиатуры",
    "Loading JSON Data": "",
    "Manipulating Entities": "Манипуляции с объектами",
    "Basic Mouse Input": "Основы управления мышью",
    "Forces and Impulses": "Силы и импульсы",
    "Animated Textures": "",
    "Animation Blending": "Смешивание анимаций",
    "Collision and Triggers": "Столкновения и триггеры",
    "Entity Picking": "",
    "Facebook API": "",
    "First Person Movement": "",
    "Intermediate": "Средний",
    "Light Cookies": "",
    "Light Halos": "",
    "More Cameras": "Больше о камерах",
    "Creating a Music Visualizer": "",
    "Procedural Levels": "",
    "Using the Asset Registry": "Использование реестра ассетов",
    "Video Textures": "",
    "Video Tutorials": "Видеоуроки",
    "Glossary": "Глоссарий",
    "User Manual": "Руководство пользователя",
    "Introduction": "Введение",
    "Animation": "Анимация",
    "Audio": "Аудио",
    "CSS": "Таблицы стилей CSS",
    "Cube Maps": "Кубические текстуры",
    "Finding Assets": "Поиск ассетов",
    "HTML": "HTML",
    "Asset Import Pipeline": "",
    "Uploading and Importing": "Загрузка и импорт",
    "Assets": "Ассеты",
    "Materials": "Материалы",
    "Phong Material": "Затенение по Фонгу",
    "Physical Material": "Физические материалы",
    "Preloading and Streaming": "Предзагрузка и стриминг",
    "Shader": "",
    "Textures": "Текстуры",
    "Building Models": "Построение моделей",
    "Exporting Assets": "Экспорт ассетов",
    "Scenes and Models": "Сцены и модели",
    "Dashboard Header": "Заголовок панели",
    "Dashboard": "Панель",
    "Overview": "Обзор",
    "Settings": "Настройки",
    "Asset Library": "Библиотека ассетов",
    "Hierarchy": "Иерархия",
    "Editor": "",
    "Inspector": "Инспектор",
    "Keyboard Shortcuts": "Горячие клавиши",
    "Loading Screen": "",
    "Menu and Toolbar": "Меню и панель инструментов",
    "Scenes": "Сцены",
    "Viewport": "Вид",
    "Cameras": "",
    "File Format": "",
    "Graphics": "",
    "Particles": "",
    "Lighting": "",
    "Lightmaps": "",
    "Lights": "",
    "Shadows": "Тени",
    "Physically Based Rendering": "",
    "Physical Materials": "",
    "Bloom Effect": "Bloom эффект",
    "Brightness-Contrast Effect": "Эффект яркости-контрастности",
    "FXAA Effect": "FXAA сглаживание",
    "Hue-Saturation Effect": "Эффект тона-насыщенности",
    "Post Effects": "Постэффекты",
    "Sepia Effect": "Эффект сепия",
    "Vignette Effect": "Эффект виньетки",
    "Optimization Guidelines": "",
    "Optimization": "",
    "Profiler": "",
    "Creating Organizations": "",
    "Organizations": "",
    "Managing Organizations": "",
    "Audio Listener": "Аудио слушатель",
    "Camera": "Камера",
    "Collision": "Столкновение",
    "Components": "Компоненты",
    "Light": "Свет",
    "Model": "Модель",
    "Particle System": "Система частиц",
    "Rigid Body": "Твёрдое тело",
    "Script": "Сценарий",
    "Sound": "",
    "Entities": "Сущности",
    "Physics": "",
    "Account": "Аккаунт",
    "Home": "Дом",
    "Profile": "Профиль",
    "Projects": "Проекты",
    "Publishing": "Публикация",
    "Desktop": "",
    "Cocoon": "",
    "Firefox OS": "Firefox OS",
    "Mobile": "",
    "Intel XDK": "Intel XDK",
    "Chrome Web Store": "Веб магазин Chrome",
    "Communication with web pages": "",
    "Facebook": "",
    "Web": "",
    "Kongregate": "",
    "PlayCanvas Hosting": "",
    "Self-hosting for beginners": "",
    "Self-hosting": "Свой хостинг",
    "Anatomy of a script": "",
    "Code Editor": "",
    "Communication": "Связь",
    "Creating new scripts": "",
    "Debugging": "Отладка",
    "Hot Reloading": "",
    "Scripting": "Написание сценариев",
    "Loading Order": "",
    "Script Attributes": "Атрибуты сценария",
    "Version Control": "",
    "Anatomy of a Script": "Анатомия сценария",
    "Creating and attaching scripts": "Создание и привязка сценариев",
    "Events": "События",
    "Legacy Scripting": "",
    "Script Priority": "",
    "Workflow": "Рабочий процесс"
}