{
    "Search - PlayCanvas Developer Resources": "Поиск - ресурсы разработчика PlayCanvas",
    "Oh No!": "О нет!",
    "PlayCanvas Developer Resources": "Ресурсы разработчика PlayCanvas",
    "Introduction": "Введение",
    "Shader Editor": "",
    "Info Pane": "",
    "Nodes Pane": "",
    "Graph Editor": "",
    "Preview Pane": "",
    "Window Layout": "",
    "Assets Pane": "",
    "Texture Inspector": "",
    "Graph Inspector": "",
    "Inspector Pane": "",
    "Material Inspector": "",
    "Node Inspector": "",
    "Textures": "Текстуры",
    "Workflow": "Рабочий процесс",
    "Overview": "Обзор",
    "File Handling": "",
    "Materials": "Материалы",
    "Nodes": "",
    "Parameter Nodes": "",
    "Sub Graphs": "",
    "Graphs": "",
    "Material Graphs": "",
    "Render a 3D model": "Отобразить 3D модель",
    "Play a sound": "Воспроизвести звук",
    "Create a cubemap": "Создать кубическую текстуру",
    "Delete an Entity": "Удалить сущность",
    "Duplicate an Entity": "Дублировать сущность",
    "Move / Rotate / Scale an Entity": "Переместить / Повернуть / Масштабировать сущность",
    "Create a new shader": "Создать новый шейдер",
    "Play an animation": "Воспроизвести анимацию",
    "Create a skybox": "Создать скайбокс",
    "Create a shape like a box, sphere etc.": "Создать примитивы, такие как куб, сфера и т.д.",
    "Add a script": "Добавить скрипт",
    "Change the background color": "Изменить задний фон",
    "Use real-time shadows": "Использовать затенение в реальном времени",
    "Use physics": "Использовать физику",
    "Delete an asset": "Удалить ресурс",
    "Upload assets": "Загрузить ресурсы",
    "Create an Entity": "Создать сущность",
    "Add a component": "Добавить компонент",
    "Create a material": "Создать материал",
    "Change the material of a model": "",
    "Create a light": "Создать свет",
    "Remove a component": "Удалить компонент",
    "Glossary": "Глоссарий",
    "User Manual": "Руководство пользователя",
    "Made with PlayCanvas": "",
    "Your First App": "",
    "Creating an Account": "Создание аккаунта",
    "Creating Organizations": "Создание организаций",
    "Organizations": "Организации",
    "Managing Organizations": "Управление организациями",
    "Publishing": "Публикация",
    "Self-hosting": "Свой хостинг",
    "Facebook": "Facebook",
    "PlayCanvas Hosting": "Хостинг PlayCanvas",
    "Hosting using a CDN": "Хостинг с использованием CDN",
    "Self-hosting for beginners": "Самостоятельный хостинг для начинающих",
    "Communication with web pages": "Связь с веб-страницами",
    "Web": "Веб",
    "Desktop": "Рабочий стол",
    "Mobile": "Мобильный",
    "Apache Cordova": "",
    "Facebook Playable Ad": "",
    "Snapchat Playable Ad": "",
    "ironSource Playable Ad (MRAID)": "",
    "Playable Ads": "",
    "Engine-Only Users": "",
    "Code Editor": "Редактор кода",
    "Communication": "Связь",
    "Migration Guide": "",
    "Loading Order": "Очень загрузки",
    "Scripting": "Написание сценариев",
    "Script Attributes": "Атрибуты сценария",
    "Using a Custom Engine": "",
    "Hot Reloading": "Горячая перезагрузка",
    "Debugging": "Отладка",
    "Creating new scripts": "Создание новых скриптов",
    "Anatomy of a script": "Структура скрипта",
    "Optimize Scene Format": "",
    "Device Pixel Ratio": "",
    "Optimization Guidelines": "Правила оптимизации",
    "Hardware Instancing": "",
    "Profiler": "Профилировщик",
    "Mini Stats": "",
    "Performance": "Производительность",
    "Batching": "",
    "Optimizing Load Time": "",
    "Troubleshooting Performance": "Проблемы с производительностью",
    "Merging and resolving conflicts": "",
    "Branches": "",
    "Version Control": "Контроль версии",
    "View Changes": "",
    "Branch Workflows": "",
    "Checkpoints": "",
    "Animation Assets": "",
    "Anim Events": "",
    "Anim Layer Masks": "",
    "Animstategraph Assets": "",
    "Animation": "Анимация",
    "Anim Component": "",
    "Optimizing WebXR applications": "",
    "Types of XR experiences": "",
    "XR": "",
    "Using WebXR in PlayCanvas": "",
    "WebXR Input Sources in PlayCanvas": "",
    "User Interface Basics": "",
    "Input": "",
    "Text Elements": "",
    "Safe Area": "",
    "Localization": "",
    "Image Elements": "",
    "Screens": "",
    "User Interface": "",
    "Layout Groups": "",
    "Elements": "",
    "Group Elements": "",
    "Scenes": "Сцены",
    "Layout Group": "",
    "Layout Child": "",
    "Particle System": "Система частиц",
    "Sprite": "",
    "Model": "Модель",
    "Scrollview": "",
    "Button": "",
    "Camera": "Камера",
    "Scrollbar": "",
    "Script": "Сценарий",
    "Anim": "",
    "Render": "",
    "Light": "Свет",
    "Components": "Компоненты",
    "Sound": "Звук",
    "Screen": "",
    "Audio Listener": "Аудио слушатель",
    "Element": "",
    "Collision": "Столкновение",
    "Rigid Body": "Твёрдое тело",
    "Entities": "Сущности",
    "Settings": "Настройки",
    "Dashboard Header": "Заголовок панели",
    "Dashboard": "Панель",
    "Account": "Аккаунт",
    "Projects": "Проекты",
    "Home": "Дом",
    "Profile": "Профиль",
    "Assets": "Ассеты",
    "Editor API": "",
    "Menu and Toolbar": "Меню и панель инструментов",
    "Viewport": "Вид",
    "Keyboard Shortcuts": "Горячие клавиши",
    "Asset Library": "Библиотека ассетов",
    "Loading Screen": "Загрузочный экран",
    "Editor": "Редактора",
    "Inspector": "Инспектор",
    "Hierarchy": "Иерархия",
    "Assets - Get Asset File": "",
    "Projects - Archive project": "",
    "Assets - Update asset": "",
    "Assets - Delete asset": "",
    "Assets - Create asset": "",
    "Assets - Get Asset": "",
    "Apps - Get primary app": "Приложения - получить основное приложение",
    "Branches - List branches": "",
    "REST API": "REST API",
    "Apps - Get app": "Приложения - получить приложение",
    "Jobs - Get job": "Работа - получить работу",
    "Assets - List assets": "",
    "Apps - Get project apps": "Приложения - получить проекты приложений",
    "Apps - Download app": "Приложение - загрузка приложений",
    "Scenes - List scenes": "",
    "Override Diff View": "",
    "Nested Templates": "",
    "Templates": "",
    "Alternatives to ammo.js": "",
    "Ray Casting": "",
    "Physics": "Физика",
    "Trigger Volumes": "",
    "Updating ammo.js": "",
    "Forces and Impulses": "Силы и импульсы",
    "Calling the ammo.js API": "",
    "Physics Basics": "",
    "Cameras": "Камыр",
    "File Format": "Формат файла",
    "Particles": "Частицы",
    "Graphics": "Графика",
    "Layers": "",
    "Physical Materials": "Физические материалы",
    "Image Based Lighting": "",
    "Physically Based Rendering": "Отображение, основанное на физических свойствах",
    "Shadows": "Тени",
    "Lightmapping": "",
    "Ambient Occlusion": "",
    "Lights": "Источники света",
    "Lighting": "Освещение",
    "Runtime Lightmaps": "",
    "FXAA Effect": "FXAA сглаживание",
    "Bloom Effect": "Bloom эффект",
    "Vignette Effect": "Эффект виньетки",
    "Hue-Saturation Effect": "Эффект тона-насыщенности",
    "Brightness-Contrast Effect": "Эффект яркости-контрастности",
    "Post Effects": "Постэффекты",
    "Sepia Effect": "Эффект сепия",
    "CSS": "Таблицы стилей CSS",
    "Template": "",
    "Texture Atlas": "",
    "Preloading and Streaming": "Предзагрузка и стриминг",
    "Audio": "Аудио",
    "Font": "",
    "Cubemap": "",
    "Shader": "Шейдер",
    "Uploading and Importing": "Загрузка и импорт",
    "Finding Assets": "Поиск ассетов",
    "Wasm Module": "",
    "HTML": "HTML",
    "Texture Compression": "",
    "Texture": "",
    "Material": "",
    "Phong Material": "Затенение по Фонгу",
    "Physical Material": "Физические материалы",
    "Exporting Assets": "Экспорт ассетов",
    "Units": "Юниты",
    "Building Models": "Построение моделей",
    "Asset Import Pipeline": "Процесс импорта ресурсов",
    "Import Hierarchy": "",
    "9-slicing": "",
    "2D": "",
    "Sprite Editor": "",
    "Billing": "",
    "Basic Audio": "Основы об аудио",
    "Facebook API": "Facebook API",
    "Manipulating Entities": "Манипуляции с объектами",
    "Making a Simple Game - Part 2": "Создание простой игры - Часть 2",
    "Making a Simple Game - Part 5": "Создание простой игры - Часть 5",
    "Animated Textures": "Анимированные текстуры",
    "Basic Cameras": "Основы камер",
    "More Cameras": "Больше о камерах",
    "Controlling Lights": "Контроль света",
    "Anim State Graph Blending": "",
    "Video Textures": "Видео-текстуры",
    "Audio Effects": "",
    "Making a Simple Game - Part 4": "Создание простой игры - Часть 4",
    "Terrain Generation from Heightmap": "Генерация ландшафта из карты высот",
    "Basic Mouse Input": "Основы управления мышью",
    "User Interface - Progress Bar": "",
    "Creating a Music Visualizer": "Создание музыкального визуализатора",
    "Light Halos": "Отблески света",
    "Custom Post Effects": "Пользовательские пост-эффекты",
    "Light Cookies": "Запекание света",
    "Using the Tween library": "",
    "User Interface - Stats Counter": "",
    "Entity Picking": "Выбор сущностей",
    "Procedural Levels": "",
    "User Interface - Leaderboard": "",
    "Basic Keyboard Input": "Основы ввода с клавиатуры",
    "First Person Movement": "Модель движения шутера от первого лица",
    "Real Time Multiplayer": "Многопользовательская игра",
    "Making a Simple Game - Part 1": "Создание простой игры - Часть 1",
    "Basic Materials": "Основы материалов",
    "Collision and Triggers": "Столкновения и триггеры",
    "Tutorials": "Уроки",
    "Animation Blending": "Смешивание анимаций",
    "Loading JSON Data": "Загрузка информации в JSON",
    "Custom Shaders": "Пользовательские шейдеры",
    "User Interface - Buttons": "",
    "Making a Simple Game - Part 6": "Создание простой игры - Часть 6",
    "Making a Simple Game - Part 3": "Создание простой игры - Часть 3",
    "WebXR UI Interaction": "",
    "Using the Asset Registry": "Использование реестра ассетов",
    "Programmatically Creating Entities": "Программное создание сущностей"
}